#server:
#  port: 8080
#
#spring:
#  application:
#    name: api-gateway-service
#  cloud:
#    gateway:
#      routes:
#        # Identity Service routes
#        - id: identity-service-auth
#          uri: http://localhost:8081 # For local testing without service discovery
#          predicates:
#            - Path=/api/auth/**
#          filters:
#            # Rewrite /api/auth/** to /auth/** for the identity-service
#            - StripPrefix=1 # Removes /api, so /auth/** remains. Identity service AuthController is at /auth
#
#        - id: identity-service-users
#          uri: http://localhost:8081
#          predicates:
#            - Path=/api/users/**
#          filters:
#            - StripPrefix=1 # Removes /api, so /users/** remains. Identity service UserController is at /users
#
#        # Product Catalog Service routes
#        - id: product-catalog-service-products
#          uri: http://localhost:8082
#          predicates:
#            - Path=/api/products/**
#          filters:
#            - StripPrefix=1 # Removes /api, so /products/** remains. Product service ProductController is at /products
#
#        - id: product-catalog-service-categories
#          uri: http://localhost:8082
#          predicates:
#            - Path=/api/categories/**
#          filters:
#            - StripPrefix=1 # Removes /api, so /categories/** remains. Product service CategoryController is at /categories
# Logging levels for gateway debugging
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    com.dreamcollections.services.apigateway: DEBUG
